### ISSUE TITLE
Handling Keys

### ISSUE THREAD

**Issue by flo2000ace** [jchristn/WatsonORM#2]
First of all i love the project you are making, i used orm before but the tool i used was rly stupid compared to this simple and easy solution.

One thing is it possible to handle keys? Like primary keys for auto increase and keys to link 2 databases together? And then use it in the Database Model? I have a account database and a device database a account can be linked to a device. So the device database has a key in it from the primary key from the account database. So i know which account is linked to this device.

Thanks!

**Comment by jchristn** [comment]
Hi @flo2000ace thank you for your kind words. 

I don't have any plans for natively defining foreign keys. The reason being is that 1) attributes require compile time constants and 2) it would create additional constraints on instantiation (ie type initialization ordering and finalization). 

You can of course use class properties like foreign keys without a foreign key constraint. Or, pre-initialize the tables with the foreign key constraints in place.

**Comment by flo2000ace** [comment]
Ah ok thanks, i think i will use class properties, thanks!
